server:
  port: 8081

spring:
  enable:
    scheduling: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/benchmark-kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: benchmark

